name: check
on:
  push:
    branches:
      - '**'
env:
  PROJECT_NAME: kt-math
  WORKFLOW: check
  GRADLE_OPTIONS: "--console=plain --stacktrace"
jobs:
  test-jvm:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        java-version:
          - 11
          - 17
          - 18
        jdk-dist:
          - adopt-hotspot
          - adopt-openj9
    #          - zulu
    runs-on: ${{ matrix.os }}
    name: Run tests via ${{ matrix.jdk-dist }} JDK v${{ matrix.java-version }}, on ${{ matrix.os }}
    steps:
      - name: Set ${{ matrix.jdk-dist }} JDK v${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.jdk-dist }}
          java-version: ${{ matrix.java-version }}

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Get All Tags
        run: git fetch --tags -f

      - name: Show Env
        run: gradle ${{ env.GRADLE_OPTIONS }} --version

      - name: Restore Gradle Dependencies
        run: gradle ${{ env.GRADLE_OPTIONS }}

      - name: Build Main Classes
        run: gradle ${{ env.GRADLE_OPTIONS }} jvmMainClasses

      - name: Build Test Classes
        run: gradle ${{ env.GRADLE_OPTIONS }} jvmTestClasses

      - name: Test JVM
        run: gradle ${{ env.GRADLE_OPTIONS }} jvmTest

  test-js:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        node-version:
          - '16-latest'
          - '18-latest'
          - '19-latest'
        java-version: [ 17 ]
        jdk-dist: [ adopt-hotspot ]
    runs-on: ${{ matrix.os }}
    name: Run tests via NodeJS ${{ matrix.node-version }}, on ${{ matrix.os }}
    env:
      ORG_GRADLE_PROJECT_nodeVersion: ${{ matrix.node-version }}
    steps:
      - name: Set ${{ matrix.jdk-dist }} JDK v${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.jdk-dist }}
          java-version: ${{ matrix.java-version }}

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Get All Tags
        run: git fetch --tags -f

      - name: Show Env
        run: gradle ${{ env.GRADLE_OPTIONS }} --version

      - name: Install Node
        run: gradle ${{ env.GRADLE_OPTIONS }} kotlinNodeJsSetup

      - name: Restore Gradle and Node Dependencies
        run: gradle ${{ env.GRADLE_OPTIONS }} kotlinNpmInstall

      - name: Build Main Classes
        run: gradle ${{ env.GRADLE_OPTIONS }} jsMainClasses

      - name: Build Test Classes
        run: gradle ${{ env.GRADLE_OPTIONS }} jsTestClasses

      - name: Test JS
        run: gradle ${{ env.GRADLE_OPTIONS }} jsTest